
# APP INFO CONFIGURATIONS
info.app.name=@project.artifactId@
info.app.description=Library to help developer using feign to make integration between applications.
info.app.version=@project.version@
spring.application.name=huntercodexs-spring-open-feign

# SERVER CONFIG
server.port=8080

# LOG CONFIG
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.security.oauth2=INFO

# FEIGN CONFIG
huntercodexs-spring-open-feign.client.config.logging=true
huntercodexs-spring-open-feign.client.config.retryer.period=3000
huntercodexs-spring-open-feign.client.config.retryer.max-period=10000
huntercodexs-spring-open-feign.client.config.retryer.max-attempts=3
huntercodexs-spring-open-feign.client.config.proxy.enable=false
huntercodexs-spring-open-feign.client.config.proxy.host=host.huntercodexs.proxy
huntercodexs-spring-open-feign.client.config.proxy.port=8989

# TESTS CONFIG
spring.test.parallel.enabled=false
junit.jupiter.execution.parallel.enabled=true

