package com.huntercodexs.integration.handler.enumerator;

public enum IntegrationGlobalEnum {
    CUSTOM_EXCEPTION_INTERCEPTOR,
    METHOD_ARGUMENT_VALIDATION_EXCEPTION_INTERCEPTOR_400,
    HTTP_MESSAGE_NOT_READABLE_EXCEPTION_INTERCEPTOR_400,
    MISSING_SERVLET_REQUEST_PARAMETER_EXCEPTION_INTERCEPTOR_400,
    CONSTRAINT_VIOLATION_EXCEPTION_INTERCEPTOR_400,
    HANDLER_METHOD_VALIDATION_EXCEPTION_INTERCEPTOR_400,
    HTTP_REQUEST_METHOD_NOT_SUPPORTED_EXCEPTION_INTERCEPTOR_405,
    HTTP_MEDIA_TYPE_NOT_SUPPORTED_EXCEPTION_INTERCEPTOR_415,
    CIRCUIT_BREAKER_CALL_NOT_PERMITTED_EXCEPTION_INTERCEPTOR_503,
    REST_CLIENT_EXCEPTION_INTERCEPTOR_502,
    DATA_ACCESS_RESOURCE_FAILURE_EXCEPTION_INTERCEPTOR_500,
    RATE_LIMIT_EXCEEDED_EXCEPTION_INTERCEPTOR_429,
    INTEGRATION_RETRY_EXCEEDED_EXCEPTION_INTERCEPTOR_503,
    RUNTIME_EXCEPTION_INTERCEPTOR_500,
    NULL_POINTER_EXCEPTION_INTERCEPTOR_5XX,
    GENERIC_EXCEPTION_INTERCEPTOR_5XX;
}
